rootProject.name = "Kotlin-Spring"

include(":Kotlin-Spring-Framework")
include(":Kotlin-Logger:logger-api")
include(":Kotlin-Logger:logger-impl")
include(":Kotlin-Logger:logger-temp")
include(":Kotlin-Logger:logger-test")
include(":Kotlin-Spring-Boot")
include(":Kotlin-Spring-Boot-Autoconfigure")
include(":Kotlin-Logger:logger-slf4j-impl")
include(":Kotlin-Spring-Instrument")
include(":Kotlin-Spring-Web")
include(":Kotlin-Spring-Cloud-Context")
include("Kotlin-Spring-Cloud-Common")
include(":Kotlin-Spring-Cloud:Kotlin-Spring-Cloud-Nacos:Kotlin-Spring-Cloud-Nacos-Config")
include(":Kotlin-Spring-Cloud:Kotlin-Spring-Cloud-Nacos:Kotlin-Spring-Cloud-Nacos-Discovery")