const val kotlinVersion = "1.6.10"  // kotlinVersion
const val slf4jApiVersion = "1.7.36"  // slf-api Version
const val springCoreVersion = "5.3.17" // spring-core Version
const val nettyVersion = "4.1.77.Final"  // netty Version
const val cglibVersion = "3.3.0"  // cglib Version
const val javaxAnnotationVersion = "1.3.2"  // javax.annotation Version
const val javaxInjectVersion = "1"  // javax.inject Version
const val javaxValidationVersion = "2.0.1.Final" // javax.validation Version
const val googleJsr305Version = "3.0.2" // jsr305 Version
const val junit4Version = "4.12"  // junit4 Version
const val junitVersion = "5.7.0"  // junit5 Version
const val aspectJVersion = "1.9.9"  // aspectJ Version
const val guavaVersion = "31.1-jre"  // guava Version
const val jacksonDatabindVersion = "2.13.2.2"  // jackson Version
const val gsonVersion = "2.10.1"  // gson Version
const val jansiVersion = "2.4.0"  // jansi Version
const val nacosClientVersion = "1.4.3"  // nacos Client Version
const val ribbonVersion = "2.3.0"  // ribbon Version
const val feignVersion = "11.8" // feign Version
const val apacheHttpClientVersion = "4.5.13"  // apache HttpClient Version
const val feignHttpClientVersion = "11.8"  // feign HttpClient Version
const val mybatisVersion = "3.5.10" // mybatis Version
const val servletApiVersion = "4.0.1" // servlet-api Version
const val tomcatCoreVersion = "9.0.70" // tomcat-core Version
const val logbackVersion = "1.4.5"  // logback Version
const val druidVersion = "1.2.10" // druid Version
const val mysqlVersion = "8.0.29" // mysql Version