const val kotlinVersion = "1.6.10"  // kotlinVersion
const val slf4jApiVersion = "1.7.36"  // slf-api Version
const val springCoreVersion = "5.3.17" // spring-core Version
const val nettyVersion = "4.1.77.Final"  // netty Version
const val cglibVersion = "3.3.0"  // cglib Version
const val javaxAnnotationVersion = "1.3.2"  // Javax Annotation Version
const val junitVersion = "5.7.0"  // junit Version
const val aspectJVersion = "1.9.9"  // aspectJ Version
const val guavaVersion = "31.1-jre"  // guava Version
const val jacksonDatabindVersion = "2.13.2.2"  // jackson Version
const val jansiVersion = "2.4.0"  // jansi Version
const val nacosClientVersion = "1.4.3"  // nacos Client Version
const val ribbonVersion = "2.3.0"  // ribbon Version
const val feignVersion = "11.8" // feign Version
const val apacheHttpClientVersion = "4.5.13"  // apache HttpClient Version
const val feignHttpClientVersion = "11.8"  // feign HttpClient Version